#!/bin/sh -l
#SBATCH --nodes=1
#SBATCH --time=72:00:00
#SBATCH --qos=gpu
#SBATCH --gres=gpu:1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem 80GB
#SBATCH --partition=gpu

# port
#ipnport=$(shuf -i8000-9999 -n1)
#ipnport=44999

# load module
module load gcc/9.3.0-cuda cuda/11.0.2

# activate anaconda
source /home/abriata/miniconda3/bin/activate
conda activate af2

# launch jupyter lab
#jupyter-lab --no-browser --port=${ipnport} --ip=$(hostname -i)
python AlphaFold2_advanced.py
